version: 1
default_environment: dev
project_id: f7cf7071-0cc0-450b-bfa1-3f2f41dc5815
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      host: localhost
      port: 5432
      user: postgres
      password: cd2153
      database: northwind
      default_replication_method: FULL_TABLE
      filter_schemas: [public]
      max_tap_batch_size: 1000
      ssl_enable: false
    select:
    - public-categories.*
    - public-customer_customer_demo.*
    - public-customer_demographics.*
    - public-customers.*
    - public-employee_territories.*
    - public-employees.*
    - public-orders.*
    - public-products.*
    - public-region.*
    - public-shippers.*
    - public-suppliers.*
    - public-territories.*
    - public-us_states.*

  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: categories
        path: ${CSV_OUTPUT_PATH}/public-categories.csv
        keys: [category_id]
        delimiter: ','
        header: true

      - entity: customers
        path: ${CSV_OUTPUT_PATH}/public-customers.csv
        keys: [customer_id]
        header: true

      - entity: employee_territories
        path: ${CSV_OUTPUT_PATH}/public-employee_territories.csv
        keys: [employee_id, territory_id]
        header: true

      - entity: employees
        path: ${CSV_OUTPUT_PATH}/public-employees.csv
        keys: [employee_id]
        header: true

      - entity: order
        path: ${CSV_OUTPUT_PATH}/public-orders.csv
        keys: [order_id]
        header: true

      - entity: products
        path: ${CSV_OUTPUT_PATH}/public-products.csv
        keys: [product_id]
        delimiter: ','
        header: true

      - entity: region
        path: ${CSV_OUTPUT_PATH}/public-region.csv
        keys: [region_id]
        delimiter: ','
        header: true

      - entity: shippers
        path: ${CSV_OUTPUT_PATH}/public-shippers.csv
        keys: [shipper_id]
        delimiter: ','
        header: true

      - entity: suppliers
        path: ${CSV_OUTPUT_PATH}/public-suppliers.csv
        keys: [supplier_id]
        delimiter: ','
        header: true

      - entity: territories
        path: ${CSV_OUTPUT_PATH}/public-territories.csv
        keys: [territory_id]
        delimiter: ','
        header: true

      - entity: us_states
        path: ${CSV_OUTPUT_PATH}/public-us_states.csv
        keys: [state_id]
        delimiter: ','
        header: true

      - entity: order_details
        path: ${CSV_DETAILS_OUTPUT_PATH}/order_details.csv
        keys: [order_id, product_id]
        delimiter: ','
        header: true

  - name: tap-csv-details
    inherit_from: tap-csv
    config:
      files:
      - entity: order_details
        path: data/order_details.csv
        keys: [order_id, product_id]
        delimiter: ','
        quotechar: '"'

  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      output_path: ${CSV_OUTPUT_PATH}

  - name: target-csv-details
    inherit_from: target-csv
    config:
      output_path: ${CSV_DETAILS_OUTPUT_PATH}

  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      host: localhost
      port: 5432
      user: postgres
      password: cd2153
      database: northwind-target
      default_target_schema: public
      max_tap_batch_size: 1000
      ssl_enable: false
jobs:
- name: tap-postgres-to-target-csv
  tasks:
  - tap-postgres target-csv
- name: tap-csv-to-target-csv
  tasks:
  - tap-csv-details target-csv
- name: tap-csv-to-target-postgres
  tasks:
  - tap-csv target-postgres
schedules:
- name: northwind-scheduler-postgres-csv
  interval: '@daily'
  job: tap-postgres-to-target-csv
- name: northwind-scheduler-csv-csv
  interval: '@daily'
  job: tap-csv-to-target-csv
- name: northwind-scheduler-csv-postgres
  interval: '@daily'
  job: tap-csv-to-target-postgres
